### ISSUE TITLE
Minio healthcheck is outdated

### ISSUE THREAD

**Issue by cinsort** [rodrigobdz/docker-compose-healthchecks#1]
As discribed in https://github.com/minio/minio/issues/18373, curl was removed from minio dockerfile.

Now we should use [healthcheck](https://github.com/minio/minio/issues/18373#issuecomment-1790003599):

```yaml
healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
```
